services:
  aldorar-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aldorar-api
    ports:
      - "3000:3000"
    environment:
      - APP_ENV=production
      - APP_PORT=3000
    restart: unless-stopped