services:
  api-prod:
    container_name: aldorar-api-prod
    image: aldorar-api:prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    env_file:
      - prod/.env
    environment:
      NODE_ENV: production
    restart: always
    depends_on:
      - postgres-prod

  postgres-prod:
    image: postgres_prod:16-alpine
    container_name: postgres_prod
    restart: unless-stopped
    env_file:
      - prod/.env
    volumes:
      - pgdata:/var/lib/postgresql/data

  api-dev:
    container_name: aldorar-api-dev
    image: aldorar-api:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    env_file:
      - dev/.env
    environment:
      NODE_ENV: development
    restart: always
    depends_on:
      - postgres-dev

  postgres-dev:
    image: postgres_dev:16-alpine
    container_name: postgres_dev
    restart: unless-stopped
    env_file:
      - dev/.env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  